FROM python:3.10-slim

WORKDIR /app

COPY . /app

RUN chmod -R 755 /app

RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8501

CMD ["sh", "-c", "streamlit run main.py --server.port=8501 --server.address=0.0.0.0 || tail -f /dev/null"]
